version: "3"
services:
       emp:
           container_name: emp
           image: emp
           restart: always
           build: .
           ports:
             - "8888:8888"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'
